# Funding Information

"github":
  - "patreon: your-patreon-username"
  - "open-collective: your-open-collective-url"
  - "liberapay: your-liberapay-username"

# Please replace the placeholders with your actual funding information.
