#!/bin/bash

# GuardianShield Deployment Script
# Run this after getting testnet ETH

echo "🛡️ GuardianShield Contract Deployment"
echo "======================================"
echo ""
echo "📋 Pre-deployment Checklist:"
echo "✅ Smart contracts compiled successfully"
echo "✅ Hardhat configuration ready"
echo "✅ Deployment scripts prepared"
echo ""
echo "⚠️  REQUIRED BEFORE DEPLOYMENT:"
echo "1. Update .env file with:"
echo "   - ETHERSCAN_API_KEY (from etherscan.io/apis)"
echo "   - PRIVATE_KEY (your wallet's private key)"
echo "   - TREASURER_ADDRESS (trusted multi-sig partner)"
echo ""
echo "2. Get testnet ETH from:"
echo "   - https://sepoliafaucet.com"
echo "   - https://faucets.chain.link/sepolia"
echo ""
echo "3. Your wallet address: 0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf"
echo ""
echo "🚀 DEPLOYMENT COMMANDS:"
echo ""
echo "# Deploy to Sepolia Testnet (FREE)"
echo "npm run deploy:sepolia"
echo ""
echo "# Deploy to Ethereum Mainnet (COSTS REAL ETH)"
echo "npm run deploy:mainnet"
echo ""
echo "📍 AFTER DEPLOYMENT:"
echo "Your contracts will be visible at:"
echo "- Sepolia: https://sepolia.etherscan.io/address/{CONTRACT_ADDRESS}"
echo "- Mainnet: https://etherscan.io/address/{CONTRACT_ADDRESS}"
echo ""
echo "🎯 Next Steps:"
echo "1. Contracts deploy to blockchain"
echo "2. Auto-verification on Etherscan"
echo "3. Frontend updates with addresses"
echo "4. Users can interact via Web3"
echo ""