version: '3.8'

# GuardianShield Edge Computing Nodes
# Distributed threat detection at the network edge

services:
  # Lightweight Edge Agent
  edge-agent:
    build:
      context: .
      dockerfile: Dockerfile.edge
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.labels.type == edge
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
      restart_policy:
        condition: on-failure
        max_attempts: 5
    environment:
      - AGENT_TYPE=edge
      - CENTRAL_HUB_URL=${CENTRAL_HUB_URL}
      - EDGE_REGION=${EDGE_REGION:-default}
      - LOCAL_CACHE_SIZE=100MB
      - SYNC_INTERVAL=300
    volumes:
      - edge_cache:/app/cache
      - edge_logs:/app/logs
    networks:
      - edge-network

  # Local Threat Intelligence Cache
  edge-cache:
    image: redis:7-alpine
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
    environment:
      - REDIS_MAXMEMORY=100mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
    volumes:
      - edge_redis:/data
    networks:
      - edge-network
    command: >
      redis-server 
      --maxmemory 100mb 
      --maxmemory-policy allkeys-lru 
      --save 300 1 
      --appendonly yes

  # Local Analytics Engine
  edge-analytics:
    build:
      context: .
      dockerfile: Dockerfile.analytics
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.4'
          memory: 512M
    environment:
      - ANALYTICS_MODE=edge
      - LOCAL_PROCESSING=true
      - BATCH_SIZE=50
      - PROCESSING_INTERVAL=60
    volumes:
      - edge_analytics:/app/data
    networks:
      - edge-network
    depends_on:
      - edge-cache

  # Edge API Gateway
  edge-gateway:
    image: nginx:alpine
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.2'
          memory: 64M
    ports:
      - "8080:80"
    volumes:
      - ./edge/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - edge-network
    depends_on:
      - edge-agent

  # Edge Security Scanner
  edge-scanner:
    build:
      context: .
      dockerfile: Dockerfile.scanner
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
    environment:
      - SCAN_MODE=edge
      - SCAN_TARGETS=local
      - SCAN_INTERVAL=3600
    volumes:
      - edge_scans:/app/scans
    networks:
      - edge-network

  # Data Synchronizer
  edge-sync:
    build:
      context: .
      dockerfile: Dockerfile.sync
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.1'
          memory: 64M
    environment:
      - SYNC_MODE=edge_to_central
      - CENTRAL_API=${CENTRAL_API_URL}
      - SYNC_INTERVAL=300
      - COMPRESSION_ENABLED=true
    volumes:
      - edge_sync:/app/sync
    networks:
      - edge-network
    depends_on:
      - edge-cache
      - edge-analytics

  # Local Monitoring
  edge-monitor:
    image: prom/node-exporter:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.1'
          memory: 32M
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - edge-network

volumes:
  edge_cache:
  edge_logs:
  edge_redis:
  edge_analytics:
  edge_scans:
  edge_sync:

networks:
  edge-network:
    driver: overlay
    attachable: true

# Edge node configuration
configs:
  edge_config:
    external: true

# Edge deployment labels
# Add these labels to edge nodes:
# docker node update --label-add type=edge <node-id>
# docker node update --label-add region=us-west <node-id>
# docker node update --label-add datacenter=edge-01 <node-id>